name: baseline
version:  0
synopsis: Baseline for buiding Haskell programs
license: BSD3
license-file: LICENCE
author: Andrew Cowie <andrew@operationaldynamics.com>
maintainer: Andrew Cowie <andrew@operationaldynamics.com>
copyright: © 2018 Operational Dynamics Consulting Pty Ltd, and Others
tested-with: GHC == 8.4

dependencies:
 - aeson
 - async
 - attoparsec
 - base
 - bytestring
 - chronologique
 - containers
 - directory
 - filepath
 - hspec
 - HTTP
 - http-client
 - http-client-tls
 - http-streams
 - network
 - network-uri
 - prettyprinter
 - prettyprinter-ansi-terminal
 - QuickCheck
 - safe-exceptions
 - scientific
 - text
 - text-short
 - tls
 - unix
 - unordered-containers
 - vector
 - vector-algorithms
 - zlib

library:
  other-modules:
    - Nothing
